var combo = [
    {  
        image:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1629975380/cp6ivak8ii869hnhsmpa.jpg",
        name: "Dettol First Aid Kit",
        inline:"combo pack of 3 Packs",
        rate:4.6,
        ratingno:"11550 ratings",
        mrp:"MRP₹515.5512% OFF",
        price:"₹451.55",
    },
    {  
        image:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707104/apzahanhtxd22ppjfbsb.jpg",
        name: "Combo Pack of Sri Sri Tattva Tulasi Arka 30ml & 1mg Giloy 500mg 30 Capsule",
        inline:"combo pack of 2 bottles",
        rate:4.4,
        ratingno:"623 ratings",
        mrp:"MRP₹40560% OFF",
        price:"₹159",
    },
    {
        image:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1613386948/frivljebqevwdptjkodu.jpg",
        name: "Nivea Soft Light Moisturiser and 1mg Germ Protection Face Wash Combo",
        inline:"combo pack of 2 Packs",
        rate:3.8,
        ratingno:"103 ratings",
        mrp:"MRP₹46044% OFF",
        price:"₹571.65",
    },
    { 
        image:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707151/wngfmvn2n6mlxrtol1df.jpg",
        name: "Combo Pack of Sri Sri Tattva Chyawanprash 1kg & 1mg High Fiber with Pre- & Probiotics with Inulin, Guar gum, & Resistant Maltodextrin Unflavoured with Resistant Maltodextrin, Inulin and Guar Gum 200gm",
        inline:"bottle of 500 ml Shampoo",
        rate:4.2,
        ratingno:"31 ratings",
        mrp:"MRP₹49910% OFF",
        price:"₹449",
    },
    {   
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1602583485/qir6i2zlhzeddxa4mqt0.jpg",
        name: "Saffola Oats 1kg with 400gm Free",
        inline:	"bottle of 110 soft gelatin capsules",
        rate:	4.5,
        ratingno: "826 ratings",     
        mrp: "MRP₹352.9824% OFF",	
        price: "₹268.27",	
    },
    {   image:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707151/wngfmvn2n6mlxrtol1df.jpg",
        name: "Saffola Oats 1kg with 400gm Free",
        inline: "bottle of 500 soft gelatin capsules",
        rate: 4.5,
        ratingno: "2191 ratings",
        mrp: "MRP₹1217.822% OFF",
        price: "₹945",
        },
    {
       image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1601161815/cropped/zolg3xv8s5klfpfqzoil.jpg",
       name: "Combo Pack of Sri Sri Tattva Karela Jamun Juice 1000ml & 1mg Diabetes",
       inline: "bottle of 60 capsules",
       rate: 4.3,
       ratingno: "636 ratings",
       mrp: "MRP₹99555% OFF",
       price: "₹448",

    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1600147625/cropped/zpfmlvskvqr6gzwhhfwc.png",
        name: "Revital Combo Pack of Revital H 30 Capsule and Revital H Woman 30 Tablet",
        inline: "bottle of 100 tablets",
        rate: 4.2,
        ratingno: "1048  ratingss",
        mrp: "MRP₹60025% OFF",
        price: "₹449",
   
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1621833298/c2sw0gi2dw4cwdf1ecjp.jpg",
        name: "Prega News Pregnancy Test Kit",
        inline: "packet of 1 Test Kit",
        rate: 4.3,
        ratingno: "1181 ratings",
        mrp: "MRP₹5539% OFF",
        price: "₹33.55",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1606819453/cr9a2p0evnuzwvw5ksp1.jpg",
        name: "Duphalac Oral Solution Lemon",
        inline: "bottle of 450 ml Oral Solution",
        rate: 4.5,
        ratingno: "333 ratingss",
        mrp: "MRP₹517.7820% OFF",
        price: "₹414.22", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707259/fwopbainofqf7oimvwyi.jpg",
        name: "Accu-Chek Active Blood Glucometer Kit (Box of 10 Test strips Free)",
        inline: "packet of 1 Kits",
        rate: 4,
        ratingno: "856  ratingss",
        mrp: "MRP₹159923% OFF",
        price: "₹1231.23", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1629974949/kig1l1egf5xcijweblix.jpg",
        name: "Enterogermina Probiotic Supplement For Diarrhea Treatment & Restoration O",
        inline: "box of 10 bottles",
        rate: 4.6,
        ratingno: "151 ratingss",
        mrp: "MRP₹544.419% OFF",
        price: "₹440.94",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707309/ml5lhcxrmjnq6zyk6dhv.jpg",
        name: "Optimum Nutrition (ON) Gold Standard 100% Whey Protein Isolate Powder Double Rich Chocolate",
        inline: "jar of 2 lb Powder",
        rate: 4.1,
        ratingno: "98 ratingss",
        mrp: "MRP₹379919% OFF",
        price: "₹3059",
      
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1629979506/nzte0nefvtlqqdicfzh9.jpg",
        name: "Digene Acidity & Gas Relief Gel Mint",
        inline: "bottle of 450 ml Oral Gel",
        rate: 4.5,
        ratingno: "791 ratings",
        mrp: "MRP₹209.3329% OFF",
        price: "₹148.09", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1606820049/qb28shpydallvrjqumup.jpg",
        name: "Durex Air Ultra Thin Condom",
        inline: "packet of 10 condoms",
        rate: 4.2,
        ratingno: "714 ratings",
        mrp: "MRP₹22826% OFF",
        price: "₹169", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707360/uymwoqs8xtl31kyssb8y.jpg",
        name: "Baidyanath Kamini Vidrawan Ras Keshar Yukta Tablet",
        inline: "bottle of 10 gm Tablet",
        rate: 3.6,
        ratingno: "49 ratings",
        mrp: "MRP₹169820% OFFF",
        price: "₹1358", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1601446265/qdkxnbhl24dgn02m7fc4.jpg",
        name: "UV Doux Silicone Sunscreen Gel SPF 50",
        inline: "tube of 50 gm Gel",
        rate: 4.5,
        ratingno: "105 ratings",
        mrp: "MRP₹69921% OFF",
        price: "₹547", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1629974164/se3cxo2mvzgqmtogtmof.jpg",
        name: "Hansaplast Silverhealing Washproof",
        inline: "packet of 10 bandages",
        rate: 4.5,
        ratingno: "259 ratings",
        mrp: "MRP₹3321% OFF",
        price: "₹26",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707406/ntwl1rfcwiqyws5fkcqa.jpg",
        name: "Dr. Morepen Omega 3 Triple Strength 1250mg Deep Sea Fish Oil with DHA & EPA 900mg Softgel",
        inline: "bottle of 60 soft gelatin capsules",
        rate: 4.3,
        ratingno: "47 ratings",
        mrp: "MRP₹109936% OFF",
        price: "₹697",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707459/j6rhskzcdv0fxbwmyvcc.jpg",
        name: "Dettol Disinfection Combo (Lime Fresh)",
        inline: "tube of 50 gm Cream",
        rate: 4.5,
        ratingno: "1102 ratings",
        mrp: "MRP₹18929% OFF",
        price: "₹134",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707509/hto1wnsbr9nhrqsx7h2s.jpg",
        name: "Dr Morepen BG 03 Gluco One Glucose Monitoring System with Gluco One BG 03 Blood Glucose 25 Test Strip",
        inline: "box of 1 Kit",
        rate: 4,
        ratingno: "1073 ratings",
        mrp: "MRP₹116459% OFF",
        price: "₹470.64",  
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1643707562/lgbfpf6gn4kv7dtlfajg.jpg",
        name: "Lama Kamini Vidrawan Ras Keshar Yukta",
        inline: "bottle of 10 gm Tablet",
        rate: 3.8,
        ratingno: "107 ratings",
        mrp: "MRP₹169825% OFF",
        price: "₹1274", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1625140403/jmv7ffde0fjjnpbady2t.png",
        name: "Dr Morepen Combo Pack of BG-03 Glucose Meter, 50 Test Strips and 100 Lancets",
        inline: "box of 1 Combo Pack",
        rate: 4,
        ratingno: "581 ratings",
        mrp: "MRP₹5536% OFF",
        price: "₹799", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1634559631/nloq2ndgjsc0zpo9691i.jpg",
        name: "i-Can Pregnancy Test Kit",
        inline: "box of 1 Test Kit",
        rate: 4.2,
        ratingno: "218 ratings",
        mrp: "MRP₹56.418% OFF",
        price: "₹35",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1633411167/ylfuylfxrh0cvzrxopf3.jpg",
        name: "Ethiglo Face Wash",
        inline: "tube of 70 gm Face Wash",
        rate: 4.2,
        ratingno: "127 ratings",
        mrp: "MRP₹2504% OFF",
        price: "₹238",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1621836623/ahnncgar7zureu1do5h0.jpg",
        name: "KamaSutra Dotted Condom",
        inline: "packet of 20 condoms",
        rate: 4,
        ratingno: "709 ratings",
        mrp: "MRP₹20042% OFF",
        price: "₹116",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1603773969/z1bfskzxf8n6pmkoolog.jpg",
        name: "Collaflex Joint Health Supplement Granules",
        inline: "sachet of 10.2 gm Granules",
        rate: 4.2,
        ratingno: "105 ratings",
        mrp: "MRP₹10019% OFF",
        price: "₹81",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1646824093/xukpfqmvyy5chfgevv3a.jpg",
        name: "Dabur Giloy Neem Juice with Tulsi",
        inline: "bottle of 1 Ltr Juice",
        rate: 4.4,
        ratingno: "324 ratings",
        mrp: "MRP₹27015% OFF",
        price: "₹230", 
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1607061624/if0qou7t1ptcaaowcigp.jpg",
        name: "Dabur Shilajit Double Gold Capsule",
        inline: "box of 10 capsules",
        rate: 3.6,
        ratingno: "126 ratings",
        mrp: "MRP₹35010% OFF",
        price: "₹314",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1640011744/ywf5rxud6ti4hbhxnuoj.jpg",
        name: "HealthKart HK Vitals Fish Oil Omega 3 Fatty Acids Soft Gelatin Capsule",
        inline: "bottle of 60 soft gelatin capsules",
        rate: 3.9,
        ratingno: "90 ratings",
        mrp: "MRP₹69947% OFF",
        price: "₹369",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1625723968/kbyeq3hyh8bxwdqfu992.jpg",
        name: "Tata 1mg Cold Pressed Aloe Vera Juice Rejuvenates Skin & Hair with Extra Fibre",
        inline: "bottle of 1 Ltr Juice",
        rate: 4.5,
        ratingno: "84 ratings",
        mrp: "MRP₹26544% OFF",
        price: "₹148",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1629974701/hqi50gamtyablux4pozy.jpg",
        name: "Acne-UV Gel SPF 30",
        inline: "tube of 30 gm Gel",
        rate: 4.4,
        ratingno: "168 ratings",
        mrp: "MRP₹46519% OFF",
        price: "₹377.3",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1617688902/gumfiaiaxmcysctoplbw.jpg",
        name: "Invigra Delay Spray for Men",
        inline: "pump bottle of 12 gm Spray",
        rate: 3.1,
        ratingno: "183 ratings",
        mrp: "MRP₹45020% OFF",
        price: "₹360",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1607061480/ip86dnqnhfelxgbr2ijf.jpg",
        name: "2baconil 21mg Nicotine Transdermal Patch Step 1",
        inline: "packet of 7 transdermal patches",
        rate: 4,
        ratingno: "67 ratings",
        mrp: "MRP₹84021% OFF",
        price: "₹663.4",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1614084909/lyssph0tahzw21ls0vbq.jpg",
        name: "Prolyte ORS Ready To Drink Orange",
        inline: "box of 200 ml Liquid",
        rate: 4.1,
        ratingno: "32 ratings",
        mrp: "MRP₹29.445% OFF",
        price: "₹16.17",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1600105580/cropped/pqd67fpjlk5u8hf38hro.jpg",
        name: "Retino A Micro 0.04% Gel",
        inline: "tube of 15 gm Gel",
        rate: 4.3,
        ratingno: "325 ratings",
        mrp: "MRP₹43022% OFF",
        price: "₹334",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1617688902/gumfiaiaxmcysctoplbw.jpg",
        name: "FLOH Rose Oil Extract Sharp Instant Hand Rub Sanitizer",
        inline: "Canister of 5 Ltr Sanitizer",
        rate: 3.6,
        ratingno: "30 ratings",
        mrp: "MRP₹250072% OFF",
        price: "₹699",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1607061480/ip86dnqnhfelxgbr2ijf.jpg",
        name: "Accu-Chek Instant Combo of Glucometer with Free 10 Test Strips, mySugr App and 50 Test Strips",
        inline: "pump bottle of 400 ml Face Wash",
        rate: 4.5,
        ratingno: "295 ratings",
        mrp: "MRP₹3758% OFF",
        price: "₹345",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1639657470/vz15ayfklaspt9d5qunk.jpg",
        name: "Tata Soulfull Crunchy Millet Muesli (700gm Each) Buy 1 Get 1 Free Super Saver Pack",
        inline: "bottle of 1 Ltr Juice",
        rate: 4.4,
        ratingno: "33 ratings",
        mrp: "MRP₹29538% OFF",
        price: "₹183",
    },
    {
        image: "https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1618478725/nserdswbkk78ojvsyzhr.jpg",
        name: "Contour Plus Blood Glucose Test Strip",
        inline: "box of 2 lb Powder",
        rate: 3.2,
        ratingno: "17 ratings",
        mrp: "MRP₹18020% OFF",
        price: "₹3059",
    }];